// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KeyboardBattle","status":false,"description":"","parameters":{}},
{"name":"BARREY_CommonEventsInBattle","status":true,"description":"It makes the battle scene load up the parallel process common events.","parameters":{}},
{"name":"BrandonFight","status":true,"description":"Brandon Battle.","parameters":{}}
];
